### ISSUE TITLE
Error to connect  the online services using proxy in an internal network

### ISSUE THREAD

**Issue by carlos-toscano** [deep-security/smartcheck-helm#18]
Hello,

I'm having some troubles to connect the trendmicro's services through proxy configuration.

I'm setting the proxy in the overrides file for both http and https forms, but  in all pods that request resources they get this error inside the containers:

`proxyconnect tcp: dial tcp <ip>:<port> i/o timeout`
_ip and port fragments were replaced_

I've tried the installation in two different clusters. These clusters are on-prem.

The proxy server is accesible by the servers that conform the clusters, and it has the right permissions, tested in the servers terminal

if you know more info about this kind of issue, it would be really useful to setup this tool properly and test all its functionalities. Thank you.

**Comment by jessc-TM** [comment]
Hello,

You may need to configure networkPolicy.additionalOutboundPorts in your overrides to allow outbound access to your proxy.
Example overrides.yaml:
```yaml
networkPolicy:
  enabled: true
  ## additionalOutboundPorts is a list of destination port numbers that are allowed for outbound connections
  ##
  ## Default value: []
  additionalOutboundPorts:
  - 4999
  - 4998

```
